### PR TITLE
wlan_guide_settings api 

### PR DESCRIPTION
**Pull request by timvlaer**
In this PR, you find a script and some new functionality to the api to configure the Huawei 5576-320 as if you'd go through the setup webpage. 

It does the same things as what you need to do manually but via the api:
* setting the locale
* accepting the privacy policy
* set the autoupdate config
* configure the wifi ssid and the admin password

I derived this information by reverse engineering the webpage hosted by the device. 

I'll use a variant of this script to automatically configure our fleet of devices. The script still requires you to connect to the WiFi network of the device. 

I hope this can help someone in the future.

### CODE REVIEW

**Comment by Salamek** [comment]
@timvlaer and there are some lint issues see https://github.com/Salamek/huawei-lte-api/actions/runs/9963720492/job/27572212960?pr=219#step:5:19

**Comment by Salamek** [comment]
Still some lint issues https://github.com/Salamek/huawei-lte-api/actions/runs/9989084977/job/27612359830?pr=219#step:5:60

and that print^ is still not replaced/removed...

**Comment by timvlaer** [comment]
My bad @Salamek , thanks for checking. It should be good now 🤞 `tox` runs successfully locally and on github actions on my fork. 
Let me know if you have any other remarks.

**Review by Salamek — APPROVED** [review]

**Comment by Salamek** [comment]
Looks good, merging...

**Pull request merged**
