### PR TITLE
Reload and retry when needed

### PR DESCRIPTION
**Pull request by zewelor**
Added wrapper with reload and retry, to fix timeout session, without need to manual reload connection.

After this, following code works:
```
from huawei_lte_api.Client import Client
from huawei_lte_api.AuthorizedConnection import AuthorizedConnection
import time

connection = AuthorizedConnection('http://admin:MY_SUPER_TRUPER_PASSWORD@192.168.8.1/')

client = Client(connection) # This just simplifies access to separate API groups, you can use device = Device(connection) if you want

print(client.device.signal())  # Can be accessed without authorization
time.sleep(500)
print(client.device.signal())  # Can be accessed without authorization
```

### CODE REVIEW

**Comment by Salamek** [comment]
@zewelor this fixes #9 ?

**Comment by zewelor** [comment]
I'm not sure. I have only modem, without any user login.

**Comment by zewelor** [comment]
@Salamek Can you release new lib version ? I want to push improvements into Home assistant integration, and I think git version won't be accepted.

**Comment by Salamek** [comment]
@zewelor https://github.com/Salamek/huawei-lte-api/releases/tag/1.2

**Comment by zewelor** [comment]
Thank you !

**Pull request merged**
